/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSavedRouteImport } from './routes/app.saved'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppSSpaceIdRouteImport } from './routes/app.s.$spaceId'
import { Route as AppDmThreadIdRouteImport } from './routes/app.dm.$threadId'
import { Route as AppSSpaceIdIndexRouteImport } from './routes/app.s.$spaceId.index'
import { Route as AppSSpaceIdTagsRouteImport } from './routes/app.s.$spaceId.tags'
import { Route as AppSSpaceIdSettingsRouteImport } from './routes/app.s.$spaceId.settings'
import { Route as AppSSpaceIdSearchRouteImport } from './routes/app.s.$spaceId.search'
import { Route as AppSSpaceIdMembersRouteImport } from './routes/app.s.$spaceId.members'
import { Route as AppSSpaceIdForumRouteImport } from './routes/app.s.$spaceId.forum'
import { Route as AppSSpaceIdEventsRouteImport } from './routes/app.s.$spaceId.events'
import { Route as AppSSpaceIdBotsRouteImport } from './routes/app.s.$spaceId.bots'
import { Route as AppSSpaceIdBotRouteImport } from './routes/app.s.$spaceId.bot'
import { Route as ApiPublicBotTokenRouteImport } from './routes/api/public/bot/$token'
import { Route as AppSSpaceIdCChannelIdRouteImport } from './routes/app.s.$spaceId.c.$channelId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSSpaceIdRoute = AppSSpaceIdRouteImport.update({
  id: '/s/$spaceId',
  path: '/s/$spaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppDmThreadIdRoute = AppDmThreadIdRouteImport.update({
  id: '/dm/$threadId',
  path: '/dm/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppSSpaceIdIndexRoute = AppSSpaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)
const AppSSpaceIdTagsRoute = AppSSpaceIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)
const AppSSpaceIdSettingsRoute = AppSSpaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)
const AppSSpaceIdSearchRoute = AppSSpaceIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)
const AppSSpaceIdMembersRoute = AppSSpaceIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)
const AppSSpaceIdForumRoute = AppSSpaceIdForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)
const AppSSpaceIdEventsRoute = AppSSpaceIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)
const AppSSpaceIdBotsRoute = AppSSpaceIdBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)
const AppSSpaceIdBotRoute = AppSSpaceIdBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)
const ApiPublicBotTokenRoute = ApiPublicBotTokenRouteImport.update({
  id: '/api/public/bot/$token',
  path: '/api/public/bot/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSSpaceIdCChannelIdRoute = AppSSpaceIdCChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => AppSSpaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/saved': typeof AppSavedRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/dm/$threadId': typeof AppDmThreadIdRoute
  '/app/s/$spaceId': typeof AppSSpaceIdRouteWithChildren
  '/api/public/bot/$token': typeof ApiPublicBotTokenRoute
  '/app/s/$spaceId/bot': typeof AppSSpaceIdBotRoute
  '/app/s/$spaceId/bots': typeof AppSSpaceIdBotsRoute
  '/app/s/$spaceId/events': typeof AppSSpaceIdEventsRoute
  '/app/s/$spaceId/forum': typeof AppSSpaceIdForumRoute
  '/app/s/$spaceId/members': typeof AppSSpaceIdMembersRoute
  '/app/s/$spaceId/search': typeof AppSSpaceIdSearchRoute
  '/app/s/$spaceId/settings': typeof AppSSpaceIdSettingsRoute
  '/app/s/$spaceId/tags': typeof AppSSpaceIdTagsRoute
  '/app/s/$spaceId/': typeof AppSSpaceIdIndexRoute
  '/app/s/$spaceId/c/$channelId': typeof AppSSpaceIdCChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/saved': typeof AppSavedRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/dm/$threadId': typeof AppDmThreadIdRoute
  '/api/public/bot/$token': typeof ApiPublicBotTokenRoute
  '/app/s/$spaceId/bot': typeof AppSSpaceIdBotRoute
  '/app/s/$spaceId/bots': typeof AppSSpaceIdBotsRoute
  '/app/s/$spaceId/events': typeof AppSSpaceIdEventsRoute
  '/app/s/$spaceId/forum': typeof AppSSpaceIdForumRoute
  '/app/s/$spaceId/members': typeof AppSSpaceIdMembersRoute
  '/app/s/$spaceId/search': typeof AppSSpaceIdSearchRoute
  '/app/s/$spaceId/settings': typeof AppSSpaceIdSettingsRoute
  '/app/s/$spaceId/tags': typeof AppSSpaceIdTagsRoute
  '/app/s/$spaceId': typeof AppSSpaceIdIndexRoute
  '/app/s/$spaceId/c/$channelId': typeof AppSSpaceIdCChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/saved': typeof AppSavedRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/dm/$threadId': typeof AppDmThreadIdRoute
  '/app/s/$spaceId': typeof AppSSpaceIdRouteWithChildren
  '/api/public/bot/$token': typeof ApiPublicBotTokenRoute
  '/app/s/$spaceId/bot': typeof AppSSpaceIdBotRoute
  '/app/s/$spaceId/bots': typeof AppSSpaceIdBotsRoute
  '/app/s/$spaceId/events': typeof AppSSpaceIdEventsRoute
  '/app/s/$spaceId/forum': typeof AppSSpaceIdForumRoute
  '/app/s/$spaceId/members': typeof AppSSpaceIdMembersRoute
  '/app/s/$spaceId/search': typeof AppSSpaceIdSearchRoute
  '/app/s/$spaceId/settings': typeof AppSSpaceIdSettingsRoute
  '/app/s/$spaceId/tags': typeof AppSSpaceIdTagsRoute
  '/app/s/$spaceId/': typeof AppSSpaceIdIndexRoute
  '/app/s/$spaceId/c/$channelId': typeof AppSSpaceIdCChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forum'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/admin'
    | '/app/saved'
    | '/app/settings'
    | '/app/'
    | '/app/dm/$threadId'
    | '/app/s/$spaceId'
    | '/api/public/bot/$token'
    | '/app/s/$spaceId/bot'
    | '/app/s/$spaceId/bots'
    | '/app/s/$spaceId/events'
    | '/app/s/$spaceId/forum'
    | '/app/s/$spaceId/members'
    | '/app/s/$spaceId/search'
    | '/app/s/$spaceId/settings'
    | '/app/s/$spaceId/tags'
    | '/app/s/$spaceId/'
    | '/app/s/$spaceId/c/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forum'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/admin'
    | '/app/saved'
    | '/app/settings'
    | '/app'
    | '/app/dm/$threadId'
    | '/api/public/bot/$token'
    | '/app/s/$spaceId/bot'
    | '/app/s/$spaceId/bots'
    | '/app/s/$spaceId/events'
    | '/app/s/$spaceId/forum'
    | '/app/s/$spaceId/members'
    | '/app/s/$spaceId/search'
    | '/app/s/$spaceId/settings'
    | '/app/s/$spaceId/tags'
    | '/app/s/$spaceId'
    | '/app/s/$spaceId/c/$channelId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forum'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/admin'
    | '/app/saved'
    | '/app/settings'
    | '/app/'
    | '/app/dm/$threadId'
    | '/app/s/$spaceId'
    | '/api/public/bot/$token'
    | '/app/s/$spaceId/bot'
    | '/app/s/$spaceId/bots'
    | '/app/s/$spaceId/events'
    | '/app/s/$spaceId/forum'
    | '/app/s/$spaceId/members'
    | '/app/s/$spaceId/search'
    | '/app/s/$spaceId/settings'
    | '/app/s/$spaceId/tags'
    | '/app/s/$spaceId/'
    | '/app/s/$spaceId/c/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForumRoute: typeof ForumRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicBotTokenRoute: typeof ApiPublicBotTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saved': {
      id: '/app/saved'
      path: '/saved'
      fullPath: '/app/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/s/$spaceId': {
      id: '/app/s/$spaceId'
      path: '/s/$spaceId'
      fullPath: '/app/s/$spaceId'
      preLoaderRoute: typeof AppSSpaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dm/$threadId': {
      id: '/app/dm/$threadId'
      path: '/dm/$threadId'
      fullPath: '/app/dm/$threadId'
      preLoaderRoute: typeof AppDmThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/s/$spaceId/': {
      id: '/app/s/$spaceId/'
      path: '/'
      fullPath: '/app/s/$spaceId/'
      preLoaderRoute: typeof AppSSpaceIdIndexRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
    '/app/s/$spaceId/tags': {
      id: '/app/s/$spaceId/tags'
      path: '/tags'
      fullPath: '/app/s/$spaceId/tags'
      preLoaderRoute: typeof AppSSpaceIdTagsRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
    '/app/s/$spaceId/settings': {
      id: '/app/s/$spaceId/settings'
      path: '/settings'
      fullPath: '/app/s/$spaceId/settings'
      preLoaderRoute: typeof AppSSpaceIdSettingsRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
    '/app/s/$spaceId/search': {
      id: '/app/s/$spaceId/search'
      path: '/search'
      fullPath: '/app/s/$spaceId/search'
      preLoaderRoute: typeof AppSSpaceIdSearchRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
    '/app/s/$spaceId/members': {
      id: '/app/s/$spaceId/members'
      path: '/members'
      fullPath: '/app/s/$spaceId/members'
      preLoaderRoute: typeof AppSSpaceIdMembersRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
    '/app/s/$spaceId/forum': {
      id: '/app/s/$spaceId/forum'
      path: '/forum'
      fullPath: '/app/s/$spaceId/forum'
      preLoaderRoute: typeof AppSSpaceIdForumRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
    '/app/s/$spaceId/events': {
      id: '/app/s/$spaceId/events'
      path: '/events'
      fullPath: '/app/s/$spaceId/events'
      preLoaderRoute: typeof AppSSpaceIdEventsRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
    '/app/s/$spaceId/bots': {
      id: '/app/s/$spaceId/bots'
      path: '/bots'
      fullPath: '/app/s/$spaceId/bots'
      preLoaderRoute: typeof AppSSpaceIdBotsRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
    '/app/s/$spaceId/bot': {
      id: '/app/s/$spaceId/bot'
      path: '/bot'
      fullPath: '/app/s/$spaceId/bot'
      preLoaderRoute: typeof AppSSpaceIdBotRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
    '/api/public/bot/$token': {
      id: '/api/public/bot/$token'
      path: '/api/public/bot/$token'
      fullPath: '/api/public/bot/$token'
      preLoaderRoute: typeof ApiPublicBotTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/s/$spaceId/c/$channelId': {
      id: '/app/s/$spaceId/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/app/s/$spaceId/c/$channelId'
      preLoaderRoute: typeof AppSSpaceIdCChannelIdRouteImport
      parentRoute: typeof AppSSpaceIdRoute
    }
  }
}

interface AppSSpaceIdRouteChildren {
  AppSSpaceIdBotRoute: typeof AppSSpaceIdBotRoute
  AppSSpaceIdBotsRoute: typeof AppSSpaceIdBotsRoute
  AppSSpaceIdEventsRoute: typeof AppSSpaceIdEventsRoute
  AppSSpaceIdForumRoute: typeof AppSSpaceIdForumRoute
  AppSSpaceIdMembersRoute: typeof AppSSpaceIdMembersRoute
  AppSSpaceIdSearchRoute: typeof AppSSpaceIdSearchRoute
  AppSSpaceIdSettingsRoute: typeof AppSSpaceIdSettingsRoute
  AppSSpaceIdTagsRoute: typeof AppSSpaceIdTagsRoute
  AppSSpaceIdIndexRoute: typeof AppSSpaceIdIndexRoute
  AppSSpaceIdCChannelIdRoute: typeof AppSSpaceIdCChannelIdRoute
}

const AppSSpaceIdRouteChildren: AppSSpaceIdRouteChildren = {
  AppSSpaceIdBotRoute: AppSSpaceIdBotRoute,
  AppSSpaceIdBotsRoute: AppSSpaceIdBotsRoute,
  AppSSpaceIdEventsRoute: AppSSpaceIdEventsRoute,
  AppSSpaceIdForumRoute: AppSSpaceIdForumRoute,
  AppSSpaceIdMembersRoute: AppSSpaceIdMembersRoute,
  AppSSpaceIdSearchRoute: AppSSpaceIdSearchRoute,
  AppSSpaceIdSettingsRoute: AppSSpaceIdSettingsRoute,
  AppSSpaceIdTagsRoute: AppSSpaceIdTagsRoute,
  AppSSpaceIdIndexRoute: AppSSpaceIdIndexRoute,
  AppSSpaceIdCChannelIdRoute: AppSSpaceIdCChannelIdRoute,
}

const AppSSpaceIdRouteWithChildren = AppSSpaceIdRoute._addFileChildren(
  AppSSpaceIdRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDmThreadIdRoute: typeof AppDmThreadIdRoute
  AppSSpaceIdRoute: typeof AppSSpaceIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDmThreadIdRoute: AppDmThreadIdRoute,
  AppSSpaceIdRoute: AppSSpaceIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForumRoute: ForumRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicBotTokenRoute: ApiPublicBotTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
